#!/usr/bin/env python3
"""Message-schedule dependency graph for SHA-256.

The schedule recurrence
    W_t = sigma1(W_{t-2}) + W_{t-7} + sigma0(W_{t-15}) + W_{t-16},  16 <= t < 64,
makes each derived word depend directly on four earlier ones. Only the
first sixteen words carry actual message data; this script traces how
those sixteen seeds propagate, and emits two artifacts:

  figures/wschedule-deps.dot  -- Graphviz source (render: dot -Tpdf ...)
  figures/wschedule-deps.tex  -- a standalone TikZ figure, \input by
                                 sections/03-geometry.tex

The useful pattern it exposes: seed-diffusion saturates at t = 26, after
which every schedule word depends on all sixteen data words.
"""
from pathlib import Path

BACK = (2, 7, 15, 16)                 # lookback distances (t-2 via s1, t-15 via s0)
SIGMA = {2: r"\sigma_1", 15: r"\sigma_0"}   # which terms pass through a linear map
ROOT = Path(__file__).resolve().parent.parent
FIG = ROOT / "figures"


def seed_deps():
    """deps[t] = set of seed indices (0..15) that W_t transitively depends on."""
    deps = [set() for _ in range(64)]
    for t in range(16):
        deps[t] = {t}
    for t in range(16, 64):
        s = set()
        for b in BACK:
            s |= deps[t - b]
        deps[t] = s
    return deps


def first_full(deps):
    return next(t for t in range(64) if len(deps[t]) == 16)


def emit_dot(deps):
    full = first_full(deps)
    L = ["digraph W {", "  rankdir=LR; node[shape=circle,fixedsize=true,width=0.3];"]
    for t in range(64):
        if t < 16:
            L.append(f'  W{t}[label="{t}",style=filled,fillcolor="#d5e5f5"];')
        else:
            # shade by how many seeds reached (4..16)
            g = 0.90 - 0.55 * (len(deps[t]) - 4) / 12.0
            L.append(f'  W{t}[label="{t}",style=filled,fillcolor="{g:.2f} 0.25 0.95"];')
    for t in range(16, 64):
        for b in BACK:
            style = ',style=bold' if b in SIGMA else ''
            L.append(f"  W{t-b} -> W{t}[color=\"#999999\"{style}];")
    L.append(f'  label="SHA-256 message schedule: seeds W0..W15 diffuse to all '
             f'16 by W{full}"; labelloc=b;')
    L.append("}")
    (FIG / "wschedule-deps.dot").write_text("\n".join(L) + "\n")


def emit_tikz(deps):
    full = first_full(deps)
    dx = 0.205
    col = {2: "citewine", 7: "projframe", 15: "linknavy", 16: "orange!80!black"}
    P = []
    P.append("% AUTO-GENERATED by tools/wschedule_graph.py -- do not edit by hand.")
    P.append(r"\begin{tikzpicture}[font=\scriptsize, >={Stealth[length=1.4mm]}]")
    P.append(r"  \def\dx{%.3f}" % dx)
    # dependency arcs (drawn first, under the nodes)
    for t in range(16, 64):
        for b in BACK:
            src, dst = (t - b) * dx, t * dx
            P.append(r"  \draw[%s, line width=0.2pt, opacity=0.4] "
                     r"(%.3f,0) to[out=58,in=122] (%.3f,0);" % (col[b], src, dst))
    # nodes
    for t in range(64):
        x = t * dx
        if t < 16:
            P.append(r"  \fill[msgfill] (%.3f,0) circle (1.5pt);" % x)
            P.append(r"  \draw (%.3f,0) circle (1.5pt);" % x)
        else:
            lvl = 12 + int(52 * (len(deps[t]) - 4) / 12.0)   # green!12..64
            P.append(r"  \fill[projframe!%d] (%.3f,0) circle (1.4pt);" % (lvl, x))
    # full-diffusion vertical marker (strip down to the trace) + label in the
    # empty area below the saturated curve, clear of the arc weave
    xf = full * dx
    P.append(r"  \draw[dashed, black!55] (%.3f,-2.0) -- (%.3f,-0.05);" % (xf, xf))
    P.append(r"  \node[black!70, anchor=west] at (%.3f,-1.5) "
             r"{\tiny $W_{%d}$: all $16$ seeds reached};" % (xf + 0.08, full))
    # seed / derived braces BELOW the strip (clear of the arcs above)
    P.append(r"  \draw[decorate, decoration={brace, mirror, amplitude=2.5pt}] "
             r"(-0.03,-0.13) -- (%.3f,-0.13) node[midway, below=1pt] "
             r"{\tiny $16$ data seeds $W_0\dots W_{15}$};" % (15 * dx))
    P.append(r"  \draw[decorate, decoration={brace, mirror, amplitude=2.5pt}] "
             r"(%.3f,-0.13) -- (%.3f,-0.13) node[midway, below=1pt] "
             r"{\tiny $48$ derived $W_{16}\dots W_{63}$};" % (16 * dx, 63 * dx))
    # diffusion step-curve below the strip
    P.append(r"  \begin{scope}[yshift=-2.0cm]")
    P.append(r"    \draw[->, black!55] (-0.05,0) -- (%.3f,0) "
             r"node[right, black!70] {\tiny $t$};" % (64 * dx))
    P.append(r"    \draw[->, black!55] (-0.05,0) -- (-0.05,0.95) "
             r"node[above, black!70, align=center] "
             r"{\tiny seeds\\[-2pt]\tiny reached};")
    P.append(r"    \draw[black!30, dashed] (-0.05,0.8) -- (%.3f,0.8) "
             r"node[right, black!55] {\tiny $16$};" % (64 * dx))
    pts = " ".join("(%.3f,%.3f)" % (t * dx, len(deps[t]) / 16.0 * 0.8)
                   for t in range(64))
    P.append(r"    \draw[projframe, thick] plot coordinates {%s};" % pts)
    P.append(r"  \end{scope}")
    P.append(r"\end{tikzpicture}")
    (FIG / "wschedule-deps.tex").write_text("\n".join(P) + "\n")


def main():
    FIG.mkdir(exist_ok=True)
    deps = seed_deps()
    emit_dot(deps)
    emit_tikz(deps)
    counts = [len(deps[t]) for t in range(16, 64)]
    print("first full-diffusion index:", first_full(deps))
    print("seeds-reached, t=16..63:", counts)
    print("wrote figures/wschedule-deps.dot and figures/wschedule-deps.tex")


if __name__ == "__main__":
    main()
